development:
  adapter: mysql2
  database: user_manage
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: user_manage_test
  username: root
  password:
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  port: <% ENV['db_port'] %>
  host: <% ENV['db_host'] %>
  database: <% ENV['db'] %>
  username: <% ENV['db_username'] %>
  password: <% ENV['db_password'] %>
  pool: 5
  timeout: 5000
